name: Build DEB Package
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: packages/*.deb
