name: Build DEB Package
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Install Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          mv sdks-master/* ~/theos/sdks/
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          make package FINALPACKAGE=1 SYSROOT=$THEOS/sdks/iPhoneOS11.2.sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTMPlayer-deb
          path: packages/*.deb
