name: Build DEB Package
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Install Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          rm -rf ~/theos/sdks
          curl -LO https://github.com/xybp888/iOS-SDKs/releases/download/v1.0/iPhoneOS9.3.sdk.tar.xz
          mkdir -p ~/theos/sdks
          tar -xf iPhoneOS9.3.sdk.tar.xz -C ~/theos/sdks/
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Create valid liblaunch stub fallback
        run: |
          mkdir -p ~/theos/sdks/iPhoneOS9.3.sdk/usr/lib/system
          cat << 'EOF' > ~/theos/sdks/iPhoneOS9.3.sdk/usr/lib/system/liblaunch.tbd
          ---
          archs:           [ armv7, armv7s, arm64 ]
          platform:        ios
          install-name:    /usr/lib/system/liblaunch.dylib
          current-version: 1.0.0
          exports:
            - archs:       [ armv7, armv7s, arm64 ]
              symbols:     [ ___launch_setup_child ]
          ...
          EOF

      - name: Build Package
        run: |
          make package FINALPACKAGE=1 SYSROOT=$THEOS/sdks/iPhoneOS9.3.sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTMPlayer-deb
          path: packages/*.deb
